version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.1.2
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run tests
          command: bundle exec rspec
